AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  SecurityGroupIds:
    Type: CommaDelimitedList
    Default: ''
  SubnetIDs:
    Type: CommaDelimitedList
    Default: ''

Globals:
  Function:
    Timeout: 15
    VpcConfig:
      SecurityGroupIds: !Ref SecurityGroupIds
      SubnetIds: !Ref SubnetIDs

Resources:
  RDSDemoFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      Policies:
        - SSMParameterReadPolicy:
            ParameterName: !Sub lambda/*
        - SQSSendMessagePolicy:
            QueueName: !Sub lambda-rds-demo-sqs-v1
      Environment:
        Variables:
          ENV_TEST: test
      Events:
        CreateThumbnailEvent:
          Type: S3
          Properties:
            Bucket: !Ref SrcBucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                - Name: prefix
                  Value: tmp
      DeadLetterQueue:
        Type: SQS
        TargetArn: arn:aws:sqs:ap-northeast-1:083636136646:lambda-rds-demo-sqs-v1
    Metadata:
      DockerTag: latest
      DockerContext: .
      Dockerfile: Dockerfile
  SrcBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: "tatsukoni-lambda-rds-demo-upload"

Outputs:
  ResizeFunction:
    Description: "RDS Demo Function"
    Value: !GetAtt RDSDemoFunction.Arn
  ResizeFunctionIamRole:
    Description: "RDS Demo Function Role"
    Value: !GetAtt RDSDemoFunction.Arn
