AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  SecurityGroupIds:
    Type: CommaDelimitedList
    Default: ''
  SubnetIDs:
    Type: CommaDelimitedList
    Default: ''

Globals:
  Function:
    Timeout: 15
    VpcConfig:
      SecurityGroupIds: !Ref SecurityGroupIds
      SubnetIds: !Ref SubnetIDs

Resources:
  RDSDemoFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      Policies:
        - SSMParameterReadPolicy:
            ParameterName: !Sub lambda/*
      Environment:
        Variables:
          ENV_TEST: test
    Metadata:
      DockerTag: latest
      DockerContext: .
      Dockerfile: Dockerfile

Outputs:
  ResizeFunction:
    Description: "RDS Demo Function"
    Value: !GetAtt RDSDemoFunction.Arn
  ResizeFunctionIamRole:
    Description: "RDS Demo Function Role"
    Value: !GetAtt RDSDemoFunction.Arn
